import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import FloatingMenu from "@/components/Menu/Menu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Timber Cut - 3D for Woodworking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col  items-center justify-center pt-10 pb-40`}
      >
        <Image
          src={"/LOGO.png"}
          alt="Logo"
          width={100}
          height={100}
          className="hover:opacity-40"
        />
        {children}
        <FloatingMenu />
      </body>
    </html>
  );
}
